services:
  DB:
    image: postgres
    container_name: DB
    ports:
      - 5436:5432
    networks:
      - spring-postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypswd
    volumes:
      - db:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    restart: always

  faultinjection:
    image: faultinjection
    build: .
    container_name: faultinjection
    ports:
      - 8080:8080
    networks:
      - spring-postgres
      - mongo_mongo-cluster
    environment:
      - DB_URL=jdbc:postgresql://DB:5432/docker
      - DB_USER=docker
      - DB_PASSWORD=pswd-docker
      - DOCKER_HOST=unix:///var/run/docker.sock  # Ensure Java uses the correct Docker host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket inside the container
    depends_on:
      - DB
    restart: always

volumes:
  db:

networks:
  spring-postgres:
  mongo_mongo-cluster:
    external: true

