services:
  DB:
    image: postgres
    container_name: DB
    ports:
      - 5436:5432
    networks:
      - spring-postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypswd
    volumes:
      - db:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    restart: always

  faultinjection:
    image: faultinjection
    build: .
    container_name: faultinjection
    ports:
      - 8080:8080
    networks:
      - spring-postgres
    environment:
      - DB_URL=jdbc:postgresql://DB:5432/docker
      - DB_USER=docker
      - DB_PASSWORD=pswd-docker
      # Tells the Java application where to access the Docker daemon
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      # Mounts the Docker socket from host machine into the container
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - DB
    stdin_open: true
    tty: true
    restart: always

volumes:
  db:

networks:
  spring-postgres:

